site_name: Pantsbuild
site_url: https://pantsbuild.org/docs/
docs_dir: markdown
use_directory_urls: true

# Theme
theme:
  name: material
  palette:
    - scheme: default
      primary: light blue
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - scheme: slate
      primary: light blue
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: system-ui
    code: Roboto Mono
  logo: assets/images/logo.png
  favicon: assets/images/favicon.ico
  features:
    - content.action.edit
    - content.action.view
    - content.code.copy
    - navigation.indexes

markdown_extensions:
  - admonition:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite:
  - pymdownx.superfences:
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true

extra_css:
  - _stylesheets/extra.css

plugins:
  - gen-files:
      scripts:
        - generate_reference_docs.py
  - awesome-pages:
      filename: .nav.yaml
      collapse_single_pages: true
  - redirects:
      redirect_maps:
        "index.md": "introduction/welcome-to-pants.md"
  - search

# GitHub
repo_name: pantsbuild/pants
repo_url: https://github.com/pantsbuild/pants
edit_uri: edit/main/docs/markdown
